# Generated by Django 3.1.7 on 2021-03-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20210315_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring',
            name='type',
            field=models.BooleanField(default=False),
        ),
    ]
